# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log_reg_app', '0003_auto_20170923_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=222)),
                ('author', models.CharField(max_length=222)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='log_reg_app.User')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed', to='log_reg_app.User')),
            ],
        ),
    ]
