# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20170926_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='car_app.Car'),
        ),
    ]
