# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_auto_20170926_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='car',
        ),
    ]
